name: Cache Node and NPM  Dependencies
description: This action allows to cache both cache and npm Dependencies based on the package*.json file.

inputs:
    node-version:
        description: NodeJS version to use
        default: 22.x
        required: true
    working-dir:
        description: The working directory of the application
        default: .
        required: false

runs:
    using: composite
    steps:
        - name: Setup NodeJS version ${{ inputs.node-version }}
          uses: actions/setup-node@v3
          with:
              node-version: ${{ inputs.node-version }}

        - name: Cache Dependencies
          uses: actions/cache@v3
          id: cache-key
          with:
              path: ${{inputs.working-dir}}/node_modules
              key: node-modules-${{hashFiles(format('{0}/{1}',inputs.working-dir,'package-lock.json'))}}

        - name: Install the Dependencies
          if: ${{steps.cache-key.outputs.cache-hit != 'true'}}
          run: npm ci
          shell: bash
          working-directory: ${{inputs.working-dir}}
