name: Update NPM  Dependencies
description: Check if there are updates to NPM packages, and creates a PR with the updated ,'package*.json' files.

inputs:
    base-branch:
        description: The branch used as the base for the dependency updates checks
        default: main
        required: false

    target-branch:
        description: The branch from which the PR is created
        default: update-dependencies
        required: false

    working-directory:
        description: The working-directory of the project to check for dependency update
        required: true

    github-token:
        description: Authenctication token with repository access, Must have write access to the contents and pull requests
        required: true

    debug:
        description: whether the output debug message to the console
        default: "false"

outputs:
    updates-available:
        description: Whether there are updates available

runs:
    using: node20
    main: index.js
