name: 01 - building blocks

on:
    # push:
    workflow_dispatch:

jobs:
    echo-hello:
        runs-on: ubuntu-latest
        steps:
            - name: Print "Hello world"
              run: echo "Hello world!"

    echo-goodbye:
        runs-on: ubuntu-latest
        steps:
            - name: Print "Good morning"
              run: |
                  echo "Good morning"
                  exit 0
            # if exit 1 , then it will be an error
            - name: Print "goodbye"
              run: echo "goodbye!!"
