name: 02 - workflow events

on:
    workflow_dispatch:
    # schedule:
    #     - cron: "*/5 * * * *"
    # every 5 min trigger this event
    # try google for generate cron expression generator

    # push:
    # pull_request:

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: Show the trigger
              run: |
                  echo "I have  been triggered by a(n) ${{github.event_name}} event."
