name: 04 - use action

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            # 1. checkout the code from the repository
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Printing Folders
              run: ls
            # 2. install dependecies of our react app
            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: "22.x"

            - name: Install dependecies
              run: npm run ci
              working-directory: 05-actions/react-app
            # 3. execute automated test
