name: 05 - 1 -  event filter and activity type

on:
    pull_request:
        types:
            - opened
            - synchronize
        branches:
            - main
    #  this is default

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Running whenever a PR is opened or synchronized AND base branch is main"
