name: 08 - using variables

on:
    workflow_dispatch:

env:
    WORKFLOW_VAR: "i am a workflow var"

jobs:
    echo:
        runs-on: ubuntu-latest
        env:
            JOB_VAR: "i am a job var"
        steps:
            - name: Print Env variables
              env:
                  STEP_VAR: "i am a step env var"
              run: |
                  echo "step env var  : ${{env.STEP_VAR}}"
                  echo "step env var  : ${{env.JOB_VAR}}"
                  echo "step env var  : ${{env.WORKFLOW_VAR}}"

              #     echo "Environment variables  : ${{vars.ENV_VAR}}" this line is not print anything becuse we havent defined the enviroment varible keyword in step,
    echo-2:
        runs-on: ubuntu-latest
        steps:
            - name: Print  variables
              run: |
                  echo "Environment variables  : ${{vars.ENV_VAR}}"
                  echo "Repository variables  : ${{vars.REPOSITORY_VAR}}"
    echo-prod:
        runs-on: ubuntu-latest
        environment: prod
        steps:
            - name: Print  variables
              run: |
                  echo "Environment variables  : ${{vars.ENV_VAR}}"
                  echo "Repository variables  : ${{vars.REPOSITORY_VAR}}"
