name: 10 - controlling  execution flow

on:
    workflow_dispatch:
        inputs:
            pass-unit-tests:
                type: boolean
                default: true
                description: whether unit test pass or not

jobs:
    lint-build:
        runs-on: ubuntu-latest
        steps:
            - name: Lint and build
              run: |
                  echo "Linting and building project"
    unit-test:
        runs-on: ubuntu-latest
        steps:
            - name: Running unit test
              run: echo "Running unit test...."

            - name: Failing tests
              if: ${{!inputs.pass-unit-tests}}
              run: exit 1

    deploy-nonprod:
        runs-on: ubuntu-latest
        needs:
            - lint-build
            - unit-test
        steps:
            - name: Deploying non prod
              run: echo 'Deploying non prod...'

    e2e-tests:
        runs-on: ubuntu-latest
        needs:
            - deploy-nonprod
        steps:
            - name: Running e2e Test
              run: echo 'Running e2e Test...'
    load-tests:
        runs-on: ubuntu-latest
        needs:
            - deploy-nonprod
        steps:
            - name: Running load test
              run: echo 'Running load test...'

    deploy-prod:
        runs-on: ubuntu-latest
        needs:
            - e2e-tests
            - load-tests
        steps:
            - name: Deploying Production
              run: echo "Deploying to Production ..."
