name: 12  - working with outputss
on:
    workflow_dispatch:
        inputs:
            build-status:
                type: choice
                options:
                    - success
                    - failure
                default: success

jobs:
    build:
        runs-on: ubuntu-latest
        outputs:
            status: ${{steps.status-id.outputs.status}}
        steps:
            - name: Build
              id: "status-id"
              run: |
                  echo "I am building step"
                  echo "status=${{inputs.build-status}}" >> "$GITHUB_OUTPUT"

    deploy:
        runs-on: ubuntu-latest
        needs: build
        if: ${{needs.build.outputs.status == 'success'}}
        steps:
            - name: Deploy
              run: echo "I have access the build output ${{needs.build.outputs.status}}"
