name: 14 - working with artifacts

on:
    workflow_dispatch:

env:
    build-artifact-key: app-${{github.sha}}
    test-report-key: test-coverage-${{github.sha}}

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: 15-artifacts/react-app
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: "20.x"

            - name: Download cache dependencies
              uses: actions/cache@v3
              id: cache
              with:
                  path: 15-artifacts/react-app/node_modules
                  key: deps-node-modules-${{hashFiles('15-artifacts/react-app/package-lock.json')}}

            - name: Insatll dependencies
              if: steps.cache.outputs.cache-hit != 'true'
              run: npm ci

            - name: Unit Test
              run: npm run test -- --coverage

            - name: Upload Test Results
              uses: actions/upload-artifact@v4
              with:
                  name: ${{env.test-report-key}}
                  path: 15-artifacts/react-app/coverage

            - name: Build Code
              run: npm run build

            - name: Upload Build File
              uses: actions/upload-artifact@v4
              with:
                  name: ${{env.build-artifact-key}}
                  path: 15-artifacts/react-app/build

    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Download Build artifacts
              uses: actions/download-artifact@v4
              with:
                  name: ${{env.build-artifact-key}}
                  path: build

            - name: Show Folder Structure
              run: ls -R
