name: 15 - matrices

on:
    workflow_dispatch:

jobs:
    backwards-compatibility:
        runs-on: ${{ matrix.os }}
        name: ${{matrix.os}}-${{matrix.node-version}}
        strategy:
            # default is true, if any failed other will be interrupted, if it is false, if one failed, other will be continue
            fail-fast: false
            matrix:
                node-version: [18.x, 20.x, 22.x]
                os:
                    - ubuntu-latest
                    - windows-latest

                # allow to extends the configuration
                # this set only mentioned combination
                include:
                    - os: ubuntu-latest
                      node-version: 23.x
                      tag: experimental
        steps:
            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Perform some  test
              run: echo "Running tests on OS ${{matrix.os}} and nodejs ${{matrix.node-version}}"

            # - name: Fail if experimental
            #   if: matrix.tag == 'experimental'
            #   run: exit 1

            - name: Perform some test
              run: echo "Running tests on OS ${{matrix.os}} and NodeJS ${{matrix.node-version}}"

    include-example:
        runs-on: ubuntu-latest
        name: ${{matrix.color}}-${{matrix.shape}}-${{matrix.size}}-${{matrix.opacity}}
        strategy:
            matrix:
                color: [red, green]
                shape: [circle, square]
                size: [small, large]
                include:
                    # 2. But if we and completly new property it will be added every possible entry
                    - opacity: 50
                    # 1. include does not override, any existing key : value that provided in matrix
                    - color: red
                      shape: tringle
                exclude:
                    # 3. remvoe any property from final matrix
                    - shape: square
        steps:
            - name: Print variantion
              run: echo "${{matrix.color}}-${{matrix.shape}}-${{matrix.size}}-${{matrix.opacity}}"
# NOTE:
# 1. in  a matrics execution flow one of  jobs is failure, all other  jobs also  be cancalled (skipped) fail fast strategy.
