name: 17 - 2 - custom action | JS Action
run-name: 17 - 2 - custom action | JS Action | BB - ${{ inputs.base-branch }} | TB - ${{ inputs.target-branch }} | WD - ${{inputs.working-directory}}

on:
    workflow_dispatch:
        inputs:
            base-branch:
                type: string
                default: main
            target-branch:
                type: string
                default: update-dependencies
            working-directory:
                type: string
                default: 18-custom-actions/react-app
permissions:
    contents: write
    pull-requests: write

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Check for dependency updates
              uses: ./.github/actions/js-deps-update
              id: update-deps
              with:
                  base-branch: ${{inputs.base-branch}}
                  target-branch: ${{inputs.target-branch}}
                  working-directory: ${{inputs.working-directory}}
                  github-token: ${{secrets.GITHUB_TOKEN}}

            - name: Print custom action output
              run: |
                  echo "Update available : ${{steps.update-deps.outputs.updates-available}}"
