name: 18 - 1 - create reusable workflows

on:
    # this workflpw_call property makes this resubale, we can call this on within another workflow
    workflow_call:
        inputs:
            target-directory:
                type: string
                required: true
        # make availble for outside
        outputs:
            build-status:
                description: build status of building process
                value: ${{jobs.deploy.outputs.build-status}}
            url:
                description: The Url of the deployed version
                value: ${{jobs.deploy.outputs.url}}

jobs:
    deploy:
        runs-on: ubuntu-latest
        outputs:
            build-status: ${{ steps.build.outputs.build-status}}
            url: ${{ steps.url-key.outputs.url}}

        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4
            - name: Build
              id: build
              run: |
                  echo "Building using directory ${{inputs.target-directory}}"
                  echo "build-status=success" >> "$GITHUB_OUTPUT"
            - name: Deploy
              id: url-key
              run: |
                  echo "deploying build artifacts"
                  echo "url=https://google.com" >> "$GITHUB_OUTPUT"
