name: 21 - workflow security with action

on:
    pull_request:

jobs:
    js-safe-pr:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout node
              uses: actions/checkout@v4

            - name: Check PR title
              uses: ./.github/actions/security
              with:
                  pr-title: ${{github.event.pull_request.title}}
